import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Libreria reto midudev',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="relative">
        <main className="m-auto gap-4 py-4 px-8 max-w-screen-lg grid grid-rows-[60px,1fr,60px]">
          <h1 className="flex items-center justify-center text-2xl font-bold">
            Libreria de José
          </h1>
          <section>{children}</section>
          <footer className="flex items-center justify-center ">
            Por Jose
          </footer>
        </main>
      </body>
    </html>
  );
}
